const mngtobj_tree = [
    {
        "parent": "",
        "supervisor_counter": 0,
        "level": 0,
        "image_url": "/files/agrinote_upload/farm1.jpg",
        "latitude": 0,
        "longtitude": 0,
        "harvest_enabled": 1,
        "label": "Trại 01",
        "process_counter": 0,
        "abnormal_counter": 0,
        "checklist_counter": 0,
        "children": [
            {
                "parent": "",
                "supervisor_counter": 0,
                "level": 1,
                "image_url": "/files/agrinote_upload/garden1.jpg",
                "latitude": 0,
                "longtitude": 0,
                "harvest_enabled": 1,
                "label": "Vườn Bơ số 1",
                "process_counter": 1,
                "abnormal_counter": 0,
                "checklist_counter": 0,
                "children": [
                    {
                        "parent": "",
                        "supervisor_counter": 0,
                        "level": 2,
                        "latitude": 0,
                        "longtitude": 0,
                        "harvest_enabled": 0,
                        "label": "Vựa 1",
                        "process_counter": 9,
                        "abnormal_counter": 0,
                        "checklist_counter": 0,
                        "children": [],
                        "parent_id": 0,
                        "name": "Vựa 1",
                        "id": 10
                    }
                ],
                "parent_id": 0,
                "name": "Vườn Bơ số 1",
                "logo": "/files/agrinote_upload/garden1.jpg",
                "id": 3
            },
            {
                "parent": "",
                "supervisor_counter": 0,
                "level": 1,
                "image_url": "/files/agrinote_upload/garden2.jpg",
                "latitude": 0,
                "longtitude": 0,
                "harvest_enabled": 0,
                "label": "Vườn Bơ số 2",
                "process_counter": 0,
                "abnormal_counter": 0,
                "checklist_counter": 0,
                "children": [],
                "parent_id": 0,
                "name": "Vườn Bơ số 2",
                "logo": "/files/agrinote_upload/garden2.jpg",
                "id": 4
            }
        ],
        "parent_id": 0,
        "name": "Trại 01",
        "logo": "/files/agrinote_upload/farm1.jpg",
        "id": 1
    },
    {
        "parent": "",
        "supervisor_counter": 1,
        "level": 0,
        "image_url": "/files/agrinote_upload/farm2.jpg",
        "latitude": 0,
        "longtitude": 0,
"harvest_enabled": 1,
        "label": "Trại 02",
        "process_counter": 0,
        "abnormal_counter": 3,
        "checklist_counter": 0,
        "children": [
            {
                "parent": "",
                "supervisor_counter": 0,
                "level": 1,
                "image_url": "/files/agrinote_upload/dua1.jpg",
                "latitude": 0,
                "longtitude": 0,
                "harvest_enabled": 0,
                "label": "Vườn dưa 1",
                "process_counter": 10,
                "abnormal_counter": 3,
                "checklist_counter": 4,
                "children": [],
                "parent_id": 0,
                "name": "Vườn dưa 1",
                "logo": "/files/agrinote_upload/dua1.jpg",
                "id": 5
            }
        ],
        "parent_id": 0,
        "name": "Trại 02",
        "logo": "/files/agrinote_upload/farm2.jpg",
        "id": 2
    },
    {
        "parent": "",
        "supervisor_counter": 1,
        "level": 0,
        "image_url": "/files/agrinote_upload/bee farm1.jpg",
        "latitude": 0,
        "longtitude": 0,
        "harvest_enabled": 1,
        "label": "Trại ong mật",
        "process_counter": 2,
        "abnormal_counter": 5,
        "checklist_counter": 15,
        "children": [
            {
                "parent": "",
                "supervisor_counter": 1,
                "level": 1,
                "image_url": "/files/agrinote_upload/hive1.jpg",
                "latitude": 0,
                "longtitude": 0,
                "harvest_enabled": 0,
                "label": "Thùng ong số 1",
                "process_counter": 3,
                "abnormal_counter": 2,
                "checklist_counter": 12,
                "children": [],
                "parent_id": 0,
                "name": "Thùng ong số 1",
                "logo": "/files/agrinote_upload/hive1.jpg",
                "id": 7
            },
            {
                "parent": "",
                "supervisor_counter": 0,
                "level": 1,
                "image_url": "/files/agrinote_upload/hive2.jpg",
                "latitude": 0,
                "longtitude": 0,
                "harvest_enabled": 0,
                "label": "Thùng ong số 2",
                "process_counter": 11,
                "abnormal_counter": 0,
                "checklist_counter": 0,
                "children": [],
                "parent_id": 0,
                "name": "Thùng ong số 2",
                "logo": "/files/agrinote_upload/hive2.jpg",
                "id": 8
            },
            {
"parent": "",
                "supervisor_counter": 0,
                "level": 1,
                "latitude": 0,
                "longtitude": 0,
                "harvest_enabled": 0,
                "label": "Thùng ong số 3",
                "process_counter": 40,
                "abnormal_counter": 0,
                "checklist_counter": 0,
                "children": [],
                "parent_id": 0,
                "name": "Thùng ong số 3",
                "id": 25
            }
        ],
        "parent_id": 0,
        "name": "Trại ong mật",
        "logo": "/files/agrinote_upload/bee farm1.jpg",
        "id": 6
    }
]

export default mngtobj_tree;